name: sprite_sheet_cut
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  image: ^4.0.17
  path: ^1.8.3
  texture_packer:
    git:
      url: git@github.com:dgs-games-builder/game-toolkit.git
      ref: c970ea9f8ea4566c587999fb8c3d4be63f8f1692
      path: packages/texture_packer

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
